### ISSUE TITLE
Colors all black on black?

### ISSUE THREAD

**Issue by rachelkelly** [tssm/fairyfloss.vim#4]
Using Vim 7.4, OSX Sierra.  Put colorscheme into ~/.vim/colorschemes, set with `colorscheme = fairyfloss`, turned into black text on black background.  Was able to `:colorscheme default` to revert.  What am I doing wrong?  Thanks for any help.  References would be fine too if I am misunderstanding why this is happening.

**Comment by tssm** [comment]
Hi @rachelkelly,

You need to enable true colors in Vim with `set termguicolors`. As far a a I know it's available since Vim 7.4.1799.

Also you need a terminal with true-color support. I'm using iTerm2.

Tomorrow I'll update the README. Please let me know if it worked.

**Comment by fuadsaud** [comment]
Couldn't get it to work.

Tried it on both iTerm2 and Terminal, inside and outside of tmux, with and without `set termguicolors` and `let $NVIM_TUI_ENABLE_TRUE_COLOR=1`. Really don't know what's going on :(

**Comment by rachelkelly** [comment]
Sorry @tssm `termguicolors` is not a known option to my iTerm2 Vim.  Can you elaborate?  I tried `set termguicolors` within an active Vim session as well as as an addition to my ~/.vimrc.

**Comment by tssm** [comment]
Hey guys, did you check your Vim version? `termguicolors` is only available on Vim >= 7.4.1799. I don't remember the minimum Neovim version but if you use Hombrew to install it it should work because the feature has been on stable by months now

**Comment by rachelkelly** [comment]
Mine says simply 7.4, let me brew install vim rq and I'll let you know.  I want this color scheme so badly!

**Comment by rachelkelly** [comment]
Doing a `brew install vim --with-override-system-vi` and then aliasing vim to "usr/local/Cellar/vim/8.0.0176/bin/vim" to use the new vim & leave the system one in place makes this work!  Along with `set termguicolors` in the .vimrc of course.

There are still some edits I will do locally - all my `~`s disappeared which I am fond of so I will be trying to replace those.

Thank you @tssm !

**Comment by tssm** [comment]
I'm glad it worked!

> There are still some edits I will do locally - all my ~s disappeared which I am fond of so I will be trying to replace those.

Yeah, I did that because ~ has always bother me, but I'm planing to bring them back because I discover how to disable them on all color schemes 😁 So it would be awesome if you send a pull request.

**Comment by fuadsaud** [comment]
I was able to get it working with Vim 8.0 with `termguicolors` on iTerm 3. Sadly I couldn't get Neovim (on master branch) to display it correctly.
